/******************************************************
* PLEASE DO NOT EDIT THIS FILE
* the verification process may break
* ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var hbs = require("express-handlebars");
var moment = require('moment');
moment().format();
require('dotenv/config');

if (!process.env.DISABLE_XORIGIN) {
  app.use(function (req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if (!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1) {
      console.log(origin);
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.engine(".hbs", hbs({ defaultLayout: "layout", extname: ".hbs" }));
app.set('view engine', 'hbs');

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function (req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function (err, data) {
      if (err) return next(err);
      res.type('txt').send(data.toString());
    });
  });

app.route('/')
  .get(function (req, res) {
    res.render("index", {
      title: "Timestamp Microservice"
    });
  })

app.route('/:date')
  .get(function (req, res) {
    var par = req.params.date;
    console.log(par);
    var unix;
    var date;
    if (isNaN(par)) {
      unix = moment(par).valueOf();
      date = moment(par).format("MMM DD, YYYY");
    } else {
      date = moment.unix(par).format("MMM DD, YYYY");
      unix = par;
    }
    console.log(unix + " " + date);
    res.render("date", {
      title: "Time Conversion",
      unix,
      date
    })
  });

// Respond not found to all the wrong routes
app.use(function (req, res, next) {
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function (err, req, res, next) {
  if (err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }
})

app.listen(process.env.PORT, function () {
  console.log(`Node.js listening at port ${process.env.PORT}...`);
});

